services:
  frontend:
    build: ./frontend
    image: registry.code.wm.edu/waveform/waveformai/frontend:latest
    ports:
      - "8080:80"
    develop:
      watch:
      - action: sync
        path: ./frontend
        target: /app
        ignore:
        - .git/
        - package.json
        - package-lock.json
      - action: rebuild
        path: package.json
  
  backend:
    build: ./backend
    image: registry.code.wm.edu/waveform/waveformai/backend:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: waveform_ai
      DB_PASSWORD: app_password
      DB_NAME: waveform_ai
    depends_on:
      db:
        condition: service_healthy
        restart: true
    develop:
      watch:
      - action: sync
        path: ./backend
        target: /app
        ignore:
        - .git/
        - package.json
        - package-lock.json
        - __tests__/
        - Dockerfile
        - .dockerignore
      - action: rebuild
        path: package.json

  db:
    image: docker.io/library/mariadb:11.7
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_DATABASE: waveform_ai
      MARIADB_USER: waveform_ai
      MARIADB_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql