openapi: 3.0.0
info:
  title: Events API
  description: API documentation for managing events.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /events/create:
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - date
                - time
                - location
                - organizer
                - registration_deadline
              properties:
                name:
                  type: string
                  example: "Opening Ceremony"
                description:
                  type: string
                  example: "description of the opening ceremony"
                date:
                  type: string
                  format: date
                  example: "3/20/2025"
                time:
                  type: string
                  example: "8:00pm"
                location:
                  type: string
                  example: "PBK Hall"
                organizer:
                  type: string
                  example: "Events Team"
                registration_deadline:
                  type: string
                  format: date
                  example: "2/15/2025"
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    $ref: '#/components/schemas/Event'
        '400':
          description: Event already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "event with same name already exists"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Server Error"

  /events/get:
    get:
      summary: Get all events
      responses:
        '200':
          description: List of all events
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Server Error"

  /events/{id}/delete:
    delete:
      summary: Delete an event
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Event ID
      responses:
        '200':
          description: Event deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    $ref: '#/components/schemas/Event'
                  message:
                    type: string
                    example: "Event deleted successfully"
        '400':
          description: Event ID not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Event ID not provided"
        '404':
          description: Event not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Event does not exist"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Server Error"

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        time:
          type: string
        location:
          type: string
        organizer:
          type: string
        registration_deadline:
          type: string
          format: date