openapi: 3.0.0
info:
  title: Performances API
  description: API documentation for managing performances.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local development server

paths:
  /performances/create:
    post:
      summary: Create a new performance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
                - date
                - time
                - location
              properties:
                name:
                  type: string
                  example: "concert"
                description:
                  type: string
                  example: "description of the concert"
                date:
                  type: string
                  format: date
                  example: "01/20/2025"
                time:
                  type: string
                  example: "7:30"
                location:
                  type: string
                  example: "PBK Hall"
      responses:
        '200':
          description: Performance created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    $ref: '#/components/schemas/Performance'
        '400':
          description: Performance already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "a performance with same name already exists"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Server error"

  /performances/get:
    get:
      summary: Get all performances
      responses:
        '200':
          description: List of all performances
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      $ref: '#/components/schemas/Performance'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Server error"

  /performances/{id}/delete:
    delete:
      summary: Delete a performance
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Performance ID
      responses:
        '200':
          description: Performance deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    $ref: '#/components/schemas/Performance'
                  message:
                    type: string
                    example: "Performance deleted successfully"
        '400':
          description: Performance ID not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Performance ID not provided"